# Generated by Django 3.0.4 on 2020-03-31 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Precision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.TextField(blank=True)),
                ('modelo', models.TextField(blank=True, null=True)),
                ('calificacion', models.TextField(blank=True, null=True)),
                ('sistema_recomendacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'precision',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Televisor',
            fields=[
                ('modelo', models.TextField(primary_key=True, serialize=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('marca', models.TextField(blank=True, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('tamanopantalla', models.TextField(blank=True, null=True)),
                ('resolucion', models.TextField(blank=True, null=True)),
                ('tipodisplay', models.TextField(blank=True, null=True)),
                ('urlwalmart', models.TextField(blank=True, null=True)),
                ('urlbb', models.TextField(blank=True, null=True)),
                ('calificacionwalmart', models.FloatField(blank=True, null=True)),
                ('activo', models.BooleanField()),
                ('datos_otra_tabla', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'televisor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Televisorbb',
            fields=[
                ('modelo', models.TextField(primary_key=True, serialize=False)),
                ('marca', models.TextField(blank=True, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('tamanopantalla', models.TextField(blank=True, null=True)),
                ('resolucion', models.TextField(blank=True, null=True)),
                ('tipodisplay', models.TextField(blank=True, null=True)),
                ('urlbb', models.TextField(blank=True, null=True)),
                ('calificacionbb', models.FloatField(blank=True, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'televisorbb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Televisorwalmart',
            fields=[
                ('modelo', models.TextField(primary_key=True, serialize=False)),
                ('marca', models.TextField(blank=True, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('tamanopantalla', models.TextField(blank=True, null=True)),
                ('resolucion', models.TextField(blank=True, null=True)),
                ('tipodisplay', models.TextField(blank=True, null=True)),
                ('urlwalmart', models.TextField(blank=True, null=True)),
                ('calificacionwalmart', models.FloatField(blank=True, null=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                'db_table': 'televisorwalmart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('correo', models.TextField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('contrasena', models.TextField()),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('correo', models.OneToOneField(db_column='correo', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Recomendacion.Usuario')),
                ('calificacionusuario', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calificacion',
                'managed': False,
            },
        ),
    ]
